---
version: "3"

services:
  prometheus:
    image: prom/prometheus:v3.6.0-rc.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:12.2.0-17449462949-ubuntu
    restart: unless-stopped
    container_name: grafana
    expose:
      - "3000"
    env_file:
      - ./grafana/.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  # Caddy automatically renews TLS certs
  caddy:
    image: caddybuilds/caddy-cloudflare:2.10.2-alpine
    restart: unless-stopped
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80" # Caddy redirects to https internally
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
    depends_on:
      - htmx-server
      - grafana
      - prometheus
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_ACCOUNT=${ACME_ACCOUNT}

  htmx-server:
    build:
      context: ./htmx
      dockerfile: Containerfile
    container_name: htmx-portfolio
    expose:
      - "8080"
    environment:
      - SMTP_KEY=${SMTP_KEY}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}

volumes:
  # Need persistent storage for TLS certs and ACME metadata for container restarts
  caddy_data:
    external: true
  caddy_config:
