---
version: "3"

services:
  prometheus:
    image: prom/prometheus:v3.6.0-rc.0
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - $PWD/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:12.2.0-17449462949-ubuntu
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
    expose:
      - "3000"
    env_file:
      - $PWD/grafana/.env
    volumes:
      - $PWD/grafana:/etc/grafana/provisioning/datasources

  caddy:
    build:
      context: $PWD/caddy
      dockerfile: Containerfile
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "2019"  # expose port for /metrics for Prometheus
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/caddy_config:/config
    depends_on:
      - htmx-server
      - grafana
      - prometheus
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_ACCOUNT=${ACME_ACCOUNT}

  htmx-server:
    build:
      context: $PWD/htmx
      dockerfile: Containerfile
    container_name: htmx-portfolio
    expose:
      - "8080"
    depends_on:
      - prometheus
      - grafana
    environment:
      - SMTP_KEY=${SMTP_KEY}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}

volumes:
  # Need persistent storage for TLS certs and ACME metadata for container restarts
  caddy_data:
    external: true
  caddy_config:
