---
version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    expose:
      - "9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - "3000"
    restart: unless-stopped
    env_file:
      - ./grafana/.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  # Caddy automatically renews TLS certs
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80" # Caddy redirects to https internally
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - htmx-server
      - grafana
      - prometheus
    restart: unless-stopped

  htmx-server:
    build:
      context: ./htmx
      dockerfile: Dockerfile
    container_name: htmx-portfolio
    expose:
      - "8080"
    env_file:
      - ./htmx/.env
