---
version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - ./grafana/.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  htmx-server:
    build:
      context: ./htmx
      dockerfile: Dockerfile
    container_name: htmx-portfolio
    ports:
      - "8080:8080"
    env_file:
      - ./htmx/.env
