FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/ratelimit@latest \
    --with github.com/caddy-dns/cloudflare@latest

FROM caddy:alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
