---
global:
  scrape_interval: "30s"
  scrape_timeout: "15s"
  evaluation_interval: "30s"

scrape_configs:
  - job_name: "nginx_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
