---
global:
  scrape_interval: "30s"
  scrape_timeout: "15s"
  evaluation_interval: "30s"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["caddy:2019"]
