FROM openresty/openresty:1.27.1.2-4-alpine-fat

RUN apk add --no-cache \
    lua5.1 \
    lua5.1-dev \
    luarocks \
    git \
    gcc \
    musl-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    curl

RUN luarocks install lua-resty-http \
 && luarocks install luasocket

RUN mkdir -p /usr/local/openresty/lualib/prometheus \
    /etc/nginx/lua \
    /var/lib/geoip \
    /var/log/nginx

COPY lua/prometheus.lua /usr/local/openresty/lualib/prometheus/
COPY lua/geoip.lua /etc/nginx/lua/
COPY lua/metrics.lua /etc/nginx/lua/

COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/

EXPOSE 80 443 8080 9145

CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
