FROM nginx:1.29-alpine

RUN apk add --no-cache \
    lua5.1 \
    lua5.1-dev \
    luarocks5.1 \
    git \
    gcc \
    musl-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    curl \

RUN luarocks-5.1 install lua-resty-http
RUN luarocks-5.1 install luasocket

RUN mkdir -p /usr/local/openresty/lualib/prometheus
RUN mkdir -p /etc/nginx/lua
RUN mkdir -p /var/lib/geoip

COPY lua/prometheus.lua /usr/local/openresty/lualib/prometheus/
COPY lua/geoip.lua /etc/nginx/lua/
COPY lua/metrics.lua /etc/nginx/lua/

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/

RUN mkdir -p /var/log/nginx

EXPOSE 80 443 8080 9145

CMD ["nginx", "-g", "daemon off;"]
