---
name: Continuous Deployment to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  deploy-gcp-vm:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update Git Repository and Containers in VM over IAP
        run: |
          echo "SMTP_KEY=${{ secrets.SMTP_KEY }}" > .env.prod
          echo "SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}" >> .env.prod
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env.prod
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env.prod
          echo "FROM_EMAIL=${{ secrets.FROM_EMAIL }}" >> .env.prod
          echo "TO_EMAIL=${{ secrets.TO_EMAIL }}" >> .env.prod

          echo "GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}" >> .env.prod
          echo "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}" >> .env.prod

          gcloud compute scp .env.prod githubactions-deploy-user@${{ secrets.GCP_INSTANCE_NAME }}:~/portfolio-site/.env.prod \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --zone=${{ secrets.GCP_ZONE }}

          shred -u .env.prod

          gcloud compute ssh githubactions-deploy-user@${{ secrets.GCP_INSTANCE_NAME }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --command="cd ~/portfolio-site && \
              git pull origin main && \
              docker compose --env-file .env.prod -f compose.prod.yaml pull && \
              docker compose --env-file .env.prod -f compose.prod.yaml build && \
              docker compose --env-file .env.prod -f compose.prod.yaml up -d --remove-orphans --force-recreate && \
              docker system prune -f && \
              shred -u .env.prod"
