---
name: Continuous Deployment to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy-gcp-vm:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to VM over IAP
        run: |
          gcloud compute ssh githubactions-deploy-user@${{ secrets.GCP_INSTANCE_NAME }} \
            --tunnel-through-iap \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --command="cd ~/portfolio-site && git pull origin main && docker compose pull && docker compose up -d"
